const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const distCssPath = path.join(__dirname, '..', 'dist', 'assets', 'style.css');
const distFlagsCssPath = path.join(__dirname, '..', 'dist', 'assets', 'flags.css');
const distIndexHtmlPath = path.join(__dirname, '..', 'dist', 'index.html');
const distAssetsDirPath = path.join(__dirname, '..', 'dist', 'assets');

if (!fs.existsSync(distCssPath)) {
  console.error('style.css was not generated by Vite:', distCssPath);
  process.exit(1);
}

// Webpack emitted this file without a charset header.
// Vite prepends @charset, so strip it to keep output parity expectations.
let css = fs.readFileSync(distCssPath, 'utf8');
css = css.replace(/^@charset "UTF-8";\s*/, '');
fs.writeFileSync(distCssPath, css);
console.log('Normalized dist/assets/style.css');

if (!fs.existsSync(distIndexHtmlPath)) {
  console.error('index.html was not generated by Vite/static copy:', distIndexHtmlPath);
  process.exit(1);
}

const cacheBusterForFile = (filePath) => {
  const contents = fs.readFileSync(filePath);
  return crypto.createHash('sha1').update(contents).digest('hex').slice(0, 10);
};

const listMatchingDistAssets = (predicate) => {
  if (!fs.existsSync(distAssetsDirPath)) {
    return [];
  }

  return fs
    .readdirSync(distAssetsDirPath)
    .filter(predicate)
    .sort()
    .map((name) => path.join(distAssetsDirPath, name));
};

const styleCssVersion = cacheBusterForFile(distCssPath);
let indexHtml = fs.readFileSync(distIndexHtmlPath, 'utf8');
indexHtml = indexHtml.replace(/assets\/style\.css(?:\?v=[A-Za-z0-9._-]+)?/g, `assets/style.css?v=${styleCssVersion}`);

if (fs.existsSync(distFlagsCssPath)) {
  const flagsCssVersion = cacheBusterForFile(distFlagsCssPath);
  indexHtml = indexHtml.replace(/assets\/flags\.css(?:\?v=[A-Za-z0-9._-]+)?/g, `assets/flags.css?v=${flagsCssVersion}`);
}

const engineEntries = listMatchingDistAssets((name) => /^engine(?:-[A-Za-z0-9]+)?\.js$/.test(name));
if (engineEntries.length > 0) {
  const preferredEngineEntry = engineEntries.find((filePath) => path.basename(filePath).startsWith('engine-')) || engineEntries[0];
  const engineAssetName = path.basename(preferredEngineEntry);
  indexHtml = indexHtml.replace(/assets\/engine(?:-[A-Za-z0-9]+)?\.js(?:\?v=[A-Za-z0-9._-]+)?/g, `assets/${engineAssetName}`);
}

fs.writeFileSync(distIndexHtmlPath, indexHtml);
console.log('Applied CSS cache-busting and updated engine entry path in dist/index.html');
