const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const distCssPath = path.join(__dirname, '..', 'dist', 'assets', 'style.css');
const distFlagsCssPath = path.join(__dirname, '..', 'dist', 'assets', 'flags.css');
const distEngineJsPath = path.join(__dirname, '..', 'dist', 'assets', 'engine.js');
const distExtraJsPath = path.join(__dirname, '..', 'dist', 'assets', 'extra.js');
const distIndexHtmlPath = path.join(__dirname, '..', 'dist', 'index.html');

if (!fs.existsSync(distCssPath)) {
  console.error('style.css was not generated by Vite:', distCssPath);
  process.exit(1);
}

// Webpack emitted this file without a charset header.
// Vite prepends @charset, so strip it to keep output parity expectations.
let css = fs.readFileSync(distCssPath, 'utf8');
css = css.replace(/^@charset "UTF-8";\s*/, '');
fs.writeFileSync(distCssPath, css);
console.log('Normalized dist/assets/style.css');

if (!fs.existsSync(distIndexHtmlPath)) {
  console.error('index.html was not generated by Vite/static copy:', distIndexHtmlPath);
  process.exit(1);
}

const cacheBusterForFile = (filePath) => {
  const contents = fs.readFileSync(filePath);
  return crypto.createHash('sha1').update(contents).digest('hex').slice(0, 10);
};

const styleCssVersion = cacheBusterForFile(distCssPath);
let indexHtml = fs.readFileSync(distIndexHtmlPath, 'utf8');
indexHtml = indexHtml.replace(/assets\/style\.css(?:\?v=[A-Za-z0-9._-]+)?/g, `assets/style.css?v=${styleCssVersion}`);

if (fs.existsSync(distFlagsCssPath)) {
  const flagsCssVersion = cacheBusterForFile(distFlagsCssPath);
  indexHtml = indexHtml.replace(/assets\/flags\.css(?:\?v=[A-Za-z0-9._-]+)?/g, `assets/flags.css?v=${flagsCssVersion}`);
}

if (fs.existsSync(distEngineJsPath)) {
  const engineJsVersion = cacheBusterForFile(distEngineJsPath);
  indexHtml = indexHtml.replace(/assets\/engine\.js(?:\?v=[A-Za-z0-9._-]+)?/g, `assets/engine.js?v=${engineJsVersion}`);
}

if (fs.existsSync(distExtraJsPath)) {
  const extraJsVersion = cacheBusterForFile(distExtraJsPath);
  indexHtml = indexHtml.replace(/assets\/extra\.js(?:\?v=[A-Za-z0-9._-]+)?/g, `assets/extra.js?v=${extraJsVersion}`);
}

fs.writeFileSync(distIndexHtmlPath, indexHtml);
console.log('Applied CSS and JS cache-busting query params in dist/index.html');
