const fs = require('fs');
const path = require('path');

const distCssPath = path.join(__dirname, '..', 'dist', 'assets', 'style.css');

if (!fs.existsSync(distCssPath)) {
  console.error('style.css was not generated by Vite:', distCssPath);
  process.exit(1);
}

// Webpack emitted this file without a charset header.
// Vite prepends @charset, so strip it to keep output parity expectations.
let css = fs.readFileSync(distCssPath, 'utf8');
css = css.replace(/^@charset "UTF-8";\s*/, '');
fs.writeFileSync(distCssPath, css);
console.log('Normalized dist/assets/style.css');
